default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  host: localhost
  username: sam
  password: samiralak

development:
  <<: *default
  database: yielloh-api_development

test:
  <<: *default
  database: yielloh-api_test

production:
  <<: *default
  database: yielloh-api_production
 